### ISSUE TITLE
Running the program under Linux

### ISSUE THREAD

**Issue by Merga189** [mstrens/PyQt#1]
One comment.

@mstrens 

> The application is written in pyqt6. So it is supposed to run on windows, mac and linux if pyqt6 (and python) is installed.
> To run it, dowload the github zip, unzip it, open a comand prompt in the folder where you unzip and enter "python app.py"

Please don't write this (Linux), if it has not been checked before.

I got it finally working here, but the way under Linux was really 'messy' to say at least.

Now that I know, that your script works, I could start with a fresh VM (Ubuntu or Debian) and work with snapshots. Try a modification, maybe a second one and make another snapshot. If that is a dead end, can go back and try another road .....

If the way is clear, those steps can be written down. 'How to run under Ubuntu 24.04'

With that information it should be manageable for Debian or LM users to get it working also.

The windows version is OK. But making the necessary experiments under a Linux system can easily ruin a running system ....

br Karl

**Comment by KeesBlokland** [comment]
Not quite sure what problems you encountered Karl, on my Ubuntu 22.04.4 LTS (yes, I know, not 24.04) I only needed to do: 

>>  pip3 install PyQt6   

to make things behave. So, you say you finally got it working etc, but what were the problems you encountered? 

There is a famous saying: ' a problem well described is a problem half solved'. 

Kees

**Comment by Merga189** [comment]
Hi Kees.

For experiments like this I do this on VMs. Have a quite fresh and untouched Xubuntu 24.04 here where ONLY the Xfce desktop is setup to suit me.

Run those commands here in sequence  

`~/Desktop/PyQt-main$ sudo apt install python3-pip`

`~/Desktop/PyQt-main$ pip3 install PyQt6`

`~/Desktop/PyQt-main$ python3 app.py`

As you state, now it should work, but I see this here 

```
Traceback (most recent call last):
  File "/home/vbox/Desktop/PyQt-main/app.py", line 17, in <module>
    from serial.tools.list_ports import comports
ModuleNotFoundError: No module named 'serial'
```

and  jasc76 comes up with .... see RCG.

For me, I know now, that the sketch is working under Buntu, but I am on Debian and Debian is pointing me over to pipx and then things look a bit different ;-)

Karl

**Comment by Merga189** [comment]
Here what I get under Debian 12

```
~/Desktop/PyQt-main$ pip3 install PyQt6

error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

Strange, that I don't get this with Buntu 24.04, but Buntu is drifting slowly off the Debian course for years now!

Could try with an actual LM and have a look, how the situation is there.

Karl

**Comment by DougWilger** [comment]
Related - macOS Sonoma on a Mac mini M2.  Works once dependencies are set up.  Note that I already had a functional Python 3 configuration, so if you haven't done that it needs to be done first,  Then make sure you have the dependencies for this program:

- pip3 install PyQT serial pyserial

Download the repository and it works using the command: 

python3 app.py
 
I was able to pull the config from a test RP2040 board, modify it, put it back and save it.  Also did a fresh install on a brand new in box Tiny2040 and applied a saved configuration and verified.

**Comment by Merga189** [comment]
First off all, we do know, that this 'app.py' is working! 

And from the experience with the 'old' oXs_Configurator, how easy this makes it for users to create both oXs_config_advanced.h and oXs_config_basic.h in a clear and compact way without going the complex oXs_config_description.h way!

But getting an average user to get 'app.py' working on his Linux system, be it LM ot something else, should not be rocket science!

I'll concentrate a bit on Buntu 24.04 and Debian 12, where with Buntu my first experiment with taking the missing parts from the Buntu sources might be totally misleading and the appropriate way is to use 'pip'. We'll see.

But Debian is another piece of cake. Because Debian points to 'pipx' instead of using 'pip' and that implements using  'venv'. 

That here was a hard task, but with good support from the developer was manageable and we found some faults!

https://discuss.ardupilot.org/t/2-linux-versions-needed-to-build-different-ap-versions/115237

I'll stay on this and if there is a easy way running this under Buntu, will post a short instruction in RCG. 

Karl

**Comment by Merga189** [comment]
Not giving up yet!

**VM guest Xubuntu 24.04**

1 - PyQt-main downloaded and unpacked on desktop

2 - sudo apt install python3-pip

3 - pip3 install PyQt6

some PATH warnings showing up! therefore reboot!

vbox@vbox:~/Desktop/PyQt-main$ echo $PATH
/home/vbox/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

Looks good to me

4 - ~/Desktop/PyQt-main$ python3 app.py (1.st try)
"ModuleNotFoundError: No module named 'serial' "

5 - pip3 install pyserial

6 - ~/Desktop/PyQt-main$ python3 app.py (2.nd try)
qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: vnc, wayland, xcb, offscreen, vkkhrdisplay, wayland-egl, minimal, minimalegl, linuxfb, eglfs.
Aborted (core dumped)

Lots of more or less helpful tips in the net when searching with those messages. Finally found those two commands

7 - sudo apt-get install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 libegl1-mesa

8 - sudo apt-get install -y libxcb-cursor-dev

THE GUI STARTS, WHEN TYPING python3 app.py

but no connection to the RP2040

~/Desktop/PyQt-main$ python3 app.py
1
start serial connect
Selected port is
ttyACM0
In handle_error
No error
In handle error : serial is not open
In handle_error
Permission denied

9 - add 'user' in /etc/group 'tty' and 'dialout' and reboot

GUI STARTS, CONNECT and get DATA

![Screenshot_2024-07-24_16-34-54](https://github.com/user-attachments/assets/4632be32-4160-457d-a55a-e3393b199f2c)


BUT TRYING TO DISCONNECT, THE WHOLE VM CRASHES AND HAS TO BE KILLED!

As the Linux implementation is working with others here, the problem must be on my side (I am not a python expert or could be a virtualbox thing) ...

For the moment I am giving up.

**Comment by Merga189** [comment]
Debian 12 is working!
